import asyncio
import httpx
from datetime import datetime, timedelta
from fastapi import FastAPI, Query
import json
app = FastAPI()


async def request_data(client, district_id, point, headers, today, end_date, test_selected):
    if district_id and point['districtId'] != district_id:
        return
    location_id = point['id']
    name = point['name']
    address = point['address']
    canSchedule = point['canSchedule']
    if canSchedule == True:
        canSchedule = 'Sim'
    else:
        canSchedule = 'Nao'
    isWalkThru = point['isWalkThru']
    if isWalkThru == True:
        isWalkThru = 'Sim'
    else:
        isWalkThru = 'Nao'

    url = f'https://api-drive.unilabs.pt/api/v1/slots?unit-id={location_id}&since={today}&until={end_date}&exam-id=1&entity-id={test_selected}'
    r = await client.get(url, headers=headers)
    if r.status_code != 200:
        return
    response = r.json()
    res = response[0]['agenda']
    for row in res:
        available_date = row['day']
        slots = row['slots']
        for slot in slots:
            if slot['seats'] > 0:
                return {'Local': name, 'Data': available_date, 'Hora Inicio': slot['since'], 'Hora Fim': slot['until'],
                        'Disponibilidade': slot['seats'], 'Morada': address, 'Permite Marcacao': canSchedule,
                        'Drive Thru': isWalkThru}


def get_fist_slot(res, name, address, canSchedule, isWalkThru):
    for row in res:
        available_date = row['day']
        slots = row['slots']
        for slot in slots:
            if slot['seats'] > 0:
                return {'name': name, 'available_date': available_date, 'since': slot['since'], 'until': slot['until'],
                        'seats': slot['seats'], 'address': address, 'canSchedule': canSchedule,
                        'isWalkThru': isWalkThru}


@app.get("/")
async def read_root(exame: str = Query('SNS', description="Acordo, SNS ou Particular"),
                    distrito: int = Query(None,
                                          description="District ID, Vazio retorna todos os distritos. Porto=13, Aveiro=1, Lisboa=11, Vila Real=17")):
    data = await unilabs(exame, distrito)
    return {'data': data}


async def unilabs(test, district_id):
    points = [{"id": 4981, "name": "Unilabs Leça da Palmeira", "districtId": 13, "districtName": "Porto",
               "address": "Avenida Combatentes da Grande Guerra, 655", "latitude": 41.193172, "longitude": -8.698382,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 4986, "name": "Unilabs Porto | Campanhã", "districtId": 13, "districtName": "Porto",
               "address": "Rua do Heroísmo, 79", "latitude": 41.146896, "longitude": -8.590364,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 4989, "name": "Unilabs Porto | Constituição 2089", "districtId": 13, "districtName": "Porto",
               "address": "Rua da Constituição, 2089", "latitude": 41.164067, "longitude": -8.622734,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5008, "name": "Unilabs Porto | Trindade", "districtId": 13, "districtName": "Porto",
               "address": "Estação da Trindade", "latitude": 41.151959, "longitude": -8.609403,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5015, "name": "Unilabs Porto | Viso", "districtId": 13, "districtName": "Porto",
               "address": "Rua Eng. Ferreira Dias, 954, loja 12 (No Centro Comercial Via Rápida)", "latitude": 41.17668,
               "longitude": -8.64766, "specialties": [1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5024, "name": "Unilabs Bolama", "email": "ucbolama@gmail.com", "districtId": 13,
               "districtName": "Porto",
               "address": "Rua do Bolama, 233", "latitude": 41.16538, "longitude": -8.6055483,
               "specialties": [1, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5033, "name": "Unilabs Porto | Lordelo do Ouro", "email": "lordelodoouro798@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Diogo Botelho, 11", "latitude": 41.15406,
               "longitude": -8.6485505,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5048, "name": "Unilabs Santa Maria da Feira | Lourosa", "districtId": 1, "districtName": "Aveiro",
               "address": "Avenida Principal 931", "latitude": 40.992658, "longitude": -8.538703,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5051, "name": "Unilabs Ovar ", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua Ferreira de Castro, 26 D", "latitude": 40.861022, "longitude": -8.622273,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5053, "name": "Unilabs Ovar | Maceda", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua de São Pedro, 1945", "latitude": 40.932569, "longitude": -8.615419,
               "specialties": [0, 1, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5075, "name": "Unilabs Aveiro | Orlando Oliveira", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua Dr. Orlando Oliveira 40/42", "latitude": 40.63934, "longitude": -8.639971,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5077, "name": "Unilabs São João da Madeira | Conde Dias Garcia", "districtId": 1,
               "districtName": "Aveiro",
               "address": "Rua Conde Dias Garcia 315", "latitude": 40.903175, "longitude": -8.491825,
               "specialties": [0, 1, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5078, "name": "Unilabs Arouca", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua Doutor Ângelo Miranda ", "latitude": 40.929599, "longitude": -8.254362,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5079, "name": "Unilabs Vale de Cambra", "districtId": 1, "districtName": "Aveiro",
               "address": "Avenida Camilo Tavares Matos 352 1 Esq", "latitude": 40.8492041, "longitude": -8.3939301,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5081, "name": "Unilabs Oliveira de Azeméis | Cesar", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua de São Pedro, Bl 3 - Loja B, Lugar da Praia", "latitude": 40.915533,
               "longitude": -8.436415,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5083, "name": "Unilabs Oliveira de Azeméis | Carregosa", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua Padre Alírio de Melo 83", "latitude": 40.883798, "longitude": -8.414782,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5084, "name": "Unilabs Oliveira de Azeméis | Arantes Oliveira", "districtId": 1,
               "districtName": "Aveiro",
               "address": "Avenida Eng. Arantes Oliveira 103 H", "latitude": 40.835862, "longitude": -8.480601,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5112, "name": "Unilabs Espinho | Avenida 24", "email": "av.24espinhobmac@gmail.com",
               "districtId": 1,
               "districtName": "Aveiro", "address": "Avenida 24, 1113", "latitude": 41.0035556, "longitude": -8.6379376,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5120, "name": "Unilabs Estarreja", "email": "dblab.estarreja@gmail.com", "districtId": 1,
               "districtName": "Aveiro", "address": "Rua Prof. Dr. Manuel Andrade, Galerias Santo António, R/C",
               "latitude": 40.75183035411982, "longitude": -8.571511742930586, "specialties": [0, 1, 100, 5],
               "canSchedule": True,
               "isWalkThru": True},
              {"id": 5121, "name": "Unilabs Estarreja | Avanca", "email": "dblab.estarreja@gmail.com", "districtId": 1,
               "districtName": "Aveiro", "address": "Rua de Santa Marinha, 12B", "latitude": 40.807248,
               "longitude": -8.573386,
               "specialties": [1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5122, "name": "Unilabs Estarreja | Pardilhó", "email": "dblab.estarreja@gmail.com",
               "districtId": 1,
               "districtName": "Aveiro", "address": "Rua Professor Pitarma, 5, R/C", "latitude": 40.79822,
               "longitude": -8.624675,
               "specialties": [1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5128, "name": "Unilabs Estarreja | Salreu", "email": "dblab.estarreja@gmail.com", "districtId": 1,
               "districtName": "Aveiro", "address": "Av. Visconde Salreu, 21 R/C", "latitude": 40.73815,
               "longitude": -8.5575127,
               "specialties": [1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5139, "name": "Unilabs Monção", "districtId": 16, "districtName": "Viana do Castelo",
               "address": "Rua Eng. Duarte Pacheco Loja 1 ", "latitude": 42.077173, "longitude": -8.482563,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5140, "name": "Unilabs Melgaço", "districtId": 16, "districtName": "Viana do Castelo",
               "address": "Rua Rio do Porto, 39", "latitude": 42.112122, "longitude": -8.257105,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5141, "name": "Unilabs Valença", "districtId": 16, "districtName": "Viana do Castelo",
               "address": "Rua Val Flores,  Bloco B", "latitude": 42.024208, "longitude": -8.645167,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5142, "name": "Unilabs Paredes de Coura", "districtId": 16, "districtName": "Viana do Castelo",
               "address": "Rua Conselheiro Miguel Dantas,", "latitude": 41.913937, "longitude": -8.566461,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5144, "name": "Unilabs Vila Nova de Cerveira", "districtId": 16,
               "districtName": "Viana do Castelo",
               "address": "Avenida Heróis do Ultramar, 55 C", "latitude": 41.942989, "longitude": -8.74368,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5170, "name": "Unilabs Vila Nova de Famalicão | Delães", "districtId": 3, "districtName": "Braga",
               "address": "Rua do Pavilhão Loja 4, Edifício Europa I", "latitude": 41.38446, "longitude": -8.414974,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5179, "name": "Unilabs Barcelos | Cândido Cunha", "email": "ucbarcelos@gmail.com", "districtId": 3,
               "districtName": "Braga", "address": "Rua Cândido Cunha, 278", "latitude": 41.534461,
               "longitude": -8.614768,
               "specialties": [1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5186, "name": "Unilabs Viana do Castelo | Jardim ", "email": "rececao.vcjardim@unilabs.com",
               "districtId": 16,
               "districtName": "Viana do Castelo", "address": "Avenida Luís de Camões, n.º 45", "latitude": 41.6948025,
               "longitude": -8.8226807, "specialties": [0, 1, 2, 3, 100, 5, 8], "canSchedule": True,
               "isWalkThru": True},
              {"id": 5198, "name": "Unilabs Porto | Campo Alegre", "districtId": 13, "districtName": "Porto",
               "address": "Rua do Campo Alegre, 231, 1º piso", "latitude": 41.152537, "longitude": -8.6330328,
               "specialties": [0, 1, 2, 3, 100, 5], "canSchedule": True, "isWalkThru": False},
              {"id": 5236, "name": "Unilabs Sintra | Cacém Agualva", "email": "575bmac@gmail.com", "districtId": 11,
               "districtName": "Lisboa", "address": "Rua Gonçalo Domingos da Silva  21 B", "latitude": 38.7746407,
               "longitude": -9.2975952, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5246, "name": "Unilabs Paredes | Largo da Feira", "districtId": 13, "districtName": "Porto",
               "address": "Largo da Feira, nº 40", "latitude": 41.205123, "longitude": -8.331264,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5247, "name": "Unilabs Amarante |1º de Maio", "districtId": 13, "districtName": "Porto",
               "address": "Avenida 1º de Maio,  R/C", "latitude": 41.27188, "longitude": -8.0778,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5250, "name": "Unilabs Penafiel", "email": "maria.natividade.santos@unilabs.com", "districtId": 13,
               "districtName": "Porto", "address": "Avenida José Júlio, 144", "latitude": 41.199713,
               "longitude": -8.290072,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5251, "name": "Unilabs Lamego", "email": "tatiana.rosa@unilabs.com", "districtId": 18,
               "districtName": "Viseu",
               "address": "Rua Almacave", "latitude": 41.099081, "longitude": -7.809966,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5292, "name": "Unilabs Chaves | Madalena", "email": "geral@laboratoriopioledo.pt",
               "districtId": 17,
               "districtName": "Vila Real", "address": "Rua Cândido Sotto Mayor, 51, R/C", "latitude": 41.73754,
               "longitude": -7.46579, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5293, "name": "Unilabs Vila Pouca de Aguiar", "email": "unilabsvilareal@gmail.com",
               "districtId": 17,
               "districtName": "Vila Real", "address": "Rua D. Agostinho Jesus Sousa", "latitude": 41.49971,
               "longitude": -7.64358,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5300, "name": "Unilabs Boticas", "email": "geral@laboratoriopioledo.pt", "districtId": 17,
               "districtName": "Vila Real", "address": "Rua Dr. Pedro Meneses,  R/Ch nº 4", "latitude": 41.68942,
               "longitude": -7.66696, "specialties": [1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5303, "name": "Unilabs Valpaços | Carrazedo de Montenegro", "email": "geral@laboratoriopioledo.pt",
               "districtId": 17, "districtName": "Vila Real", "address": "Avenida D. Dinis Lote 35 Loja R/C Dirt.",
               "latitude": 41.56393, "longitude": -7.04321, "specialties": [0, 1, 3, 100, 5], "canSchedule": True,
               "isWalkThru": True},
              {"id": 5305, "name": "Unilabs Vila Flor", "email": "ramosana170583@gmail.com", "districtId": 4,
               "districtName": "Bragança", "address": "Vila Flor, Praça D. Dinis, n.º 61",
               "latitude": 41.3080294, "longitude": -7.1610019, "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5307, "name": "Unilabs Valpaços", "email": "geral@laboratoriopioledo.pt", "districtId": 17,
               "districtName": "Vila Real", "address": "Avenida Francisco Sá Carneiro, 32", "latitude": 41.60865,
               "longitude": -7.31317, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5312, "name": "Unilabs Paredes | Lordelo", "email": "dianacatarinacunha05@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Avenida Adelino Amaro da Costa, 242", "latitude": 41.238713,
               "longitude": -8.415057, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5323, "name": "Unilabs Coimbra | Quinta da Várzea", "email": "labsilvamonteiro@gmail.com",
               "districtId": 6,
               "districtName": "Coimbra", "address": "Rua António Gonçalves, 51 Lote 16 e 17",
               "latitude": 40.19553838751953,
               "longitude": -8.432937642535586, "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5326, "name": "Unilabs Soure", "districtId": 6, "districtName": "Coimbra",
               "address": "Rua Doutor Tomás Oliveira Silva 1, Soure", "latitude": 40.059374, "longitude": -8.625582,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5358, "name": "Unilabs Guimarães | Pevidém ", "email": "rececao.pevidem@unilabs.com",
               "districtId": 3,
               "districtName": "Braga", "address": "Rua Central, 15, 1º Drt", "latitude": 41.42793,
               "longitude": -8.353092,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5377, "name": "Unilabs Guimarães | Azurém", "email": "rececao.azurem@unilabs.com", "districtId": 3,
               "districtName": "Braga", "address": "Rua Nossa Senhora da Conceição, 23 4800-163 ",
               "latitude": 41.447645,
               "longitude": 8.300149, "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5412, "name": "Unilabs Gondomar | São Cosme", "email": "claudia.carvalho.pereira@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Monte Crasto, 48 R/C Loja 31", "latitude": 41.140495,
               "longitude": -8.533673,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5414, "name": "Unilabs Vila Nova de Gaia | Canidelo", "email": "marcia.salome.soares@unilabs.com",
               "districtId": 13, "districtName": "Porto", "address": "Rua Tenente Valadim, 908", "latitude": 41.128254,
               "longitude": -8.6393822, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5416, "name": "Unilabs Vila Nova de Gaia | Rasa", "email": "andreia.sofia.castro@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua da Rasa, 274", "latitude": 41.120083, "longitude": -8.610774,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5417, "name": "Unilabs Valongo | 5 de Outubro", "districtId": 13, "districtName": "Porto",
               "address": "Avenida 5 de Outubro, 445", "latitude": 41.19339, "longitude": -8.49984,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5426, "name": "Unilabs Ermesinde |  António Castro Meireles", "districtId": 13,
               "districtName": "Porto",
               "address": "Rua D. António Castro Meireles, 52 R/C", "latitude": 41.21864, "longitude": -8.55273,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5427, "name": "Unilabs Valongo | Padrão", "districtId": 13, "districtName": "Porto",
               "address": "Rua do Padrão, 44", "latitude": 41.18883, "longitude": -8.49442,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5429, "name": "Unilabs Vila Nova de Gaia | Canelas ", "email": "maria.ferreira.dias@unilabs.com",
               "districtId": 13, "districtName": "Porto", "address": "Rua Dr. Carlos Costa, 62", "latitude": 41.083298,
               "longitude": -8.60137, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5432, "name": "Unilabs Valongo | Alfena", "districtId": 13, "districtName": "Porto",
               "address": "Rua 1º de Maio, 1831", "latitude": 41.24218, "longitude": -8.52526,
               "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5476, "name": "Unilabs Vila Nova de Gaia | Valadares", "email": "valadaresbmac@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Manuel Moreira Costa Junior, 773", "latitude": 41.0959838,
               "longitude": -8.6316256, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5496, "name": "Unilabs Bragança", "email": "lacmjmls@sapo.pt", "districtId": 4,
               "districtName": "Bragança",
               "address": "Rua Calouste Gulbenkian, 5, R/C ", "latitude": 41.80681, "longitude": -6.754008,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5503, "name": "Unilabs Mogadouro", "email": "maria.oliveira@unilabs.com", "districtId": 4,
               "districtName": "Bragança", "address": "Rua das Eiras, 108 r/c", "latitude": 41.34361,
               "longitude": -6.7121628,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5505, "name": "Unilabs Carrazeda de Ansiães", "email": "nadia.cardoso@unilabs.com",
               "districtId": 4,
               "districtName": "Bragança", "address": "Rua Luís de Camões, 826, R/C, loja 3", "latitude": 41.24265,
               "longitude": -7.305027, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5508, "name": "Unilabs Alfândega da Fé", "email": "elvira.herdeiro@unilabs.com", "districtId": 4,
               "districtName": "Bragança", "address": "Rua Camilo de Mendonça, 53, r/c drt", "latitude": 41.342115,
               "longitude": -6.963801, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5510, "name": "Unilabs Santo Tirso | São Martinho do Campo", "email": "bmacsmartinho@gmail.com",
               "districtId": 13, "districtName": "Porto", "address": "Rua José Narciso F Martins Costa, 763",
               "latitude": 41.35621,
               "longitude": -8.364854, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5511, "name": "Unilabs Póvoa de Varzim | Fontaínhas", "email": "maria.ceu.simoes@unilabs.com",
               "districtId": 13,
               "districtName": "Porto",
               "address": "Rua da Cavadinha, 38 - Loja 7 (Praceta José António Oliveira Junior - nº111)",
               "latitude": 41.414819, "longitude": -8.652972, "specialties": [1, 100, 5], "canSchedule": True,
               "isWalkThru": True},
              {"id": 5515, "name": "Unilabs Santo Tirso |  Sousa Trêpa", "email": "Rececao.SousaTrepa@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Sousa Trepa, 20", "latitude": 41.34197, "longitude": -8.4744189,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5518, "name": "Unilabs Santo Tirso | Caldas Saúde", "districtId": 13, "districtName": "Porto",
               "address": "Rua Albino Sousa Cruz, 421", "latitude": 41.36451, "longitude": -8.4889367,
               "specialties": [0, 1, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 5519, "name": "Unilabs Maia | Castelo da Maia", "email": "barbara.almeida@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Via Engenheiro Belmiro Mendes de Azevedo, 47, 1º, Sala 1",
               "latitude": 41.2599,
               "longitude": -8.6169697, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5527, "name": "Unilabs Maia | Nogueira da Maia", "email": "ana.isabel.branco@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Dr. Joaquim Nogueira dos Santos, 672", "latitude": 41.228597,
               "longitude": -8.580886, "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5536, "name": "Unilabs Trofa | Conde de São Bento", "districtId": 13, "districtName": "Porto",
               "address": "Rua Conde de São Bento, 63", "latitude": 41.3377527, "longitude": -8.5579844,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5538, "name": "Unilabs Esposende | Apúlia", "email": "vera.campinho@unilabs.com", "districtId": 3,
               "districtName": "Braga", "address": "Avenida da Praia, 15", "latitude": 41.48497, "longitude": -8.776462,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5541, "name": "Unilabs Maia | Águas Santas", "email": "claudia.lopes.neves@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua do Meilão, 480", "latitude": 41.20974, "longitude": -8.57108,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5557, "name": "Unilabs Vila do Conde |  Caxinas", "districtId": 13, "districtName": "Porto",
               "address": "Avenida Infante D. Henrique, 904", "latitude": 41.36594, "longitude": -8.760996,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5559, "name": "Unilabs Porto | Vila do Conde", "districtId": 13, "districtName": "Porto",
               "address": "Rua Dr. António José Sousa Pereira, 295", "latitude": 41.355003, "longitude": -8.748529,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5591, "name": "Unilabs Maia | Padre António", "email": "liliana.antunes@unilabs.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua Padre António, 99", "latitude": 41.233814,
               "longitude": -8.62372,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5614, "name": "Unilabs Braga | Gualtar", "districtId": 3, "districtName": "Braga",
               "address": "Rua da Lameira, 125 Fracção B", "latitude": 41.565917, "longitude": -8.387033,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5616, "name": "Unilabs Vila Nova de Famalicão | Ernesto Carvalho", "districtId": 3,
               "districtName": "Braga",
               "address": "Rua Ernesto Carvalho,  Edifício Turim Loja 10", "latitude": 41.40876, "longitude": -8.522844,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5630, "name": "Unilabs Barcelos | Praceta António Fogaça ", "districtId": 3,
               "districtName": "Braga",
               "address": "Praça António Fogaça,  Bloco 7 Fracção 8", "latitude": 41.532344, "longitude": -8.623488,
               "specialties": [1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5703, "name": "Unilabs Ferreiros", "districtId": 3, "districtName": "Braga",
               "address": "Rua Frei José Vilaça, 191 C", "latitude": 41.536716, "longitude": -8.441375,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5724, "name": "Unilabs Cantanhede ", "email": "geral.cantanhede@unilabs.com", "districtId": 6,
               "districtName": "Coimbra", "address": "Largo D. João Crisóstomo Amorim Pessoa, 28", "latitude": 40.34429,
               "longitude": -8.592162, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5732, "name": "Unilabs Seixal | Clidiral Amora", "districtId": 15, "districtName": "Setúbal",
               "address": "Rua das Flores, 12A  e  8, A e D", "latitude": 38.62016, "longitude": -9.1128383,
               "specialties": [0, 1, 2, 3, 100, 5, 7, 8], "canSchedule": True, "isWalkThru": True},
              {"id": 5733, "name": "Unilabs Torre de Moncorvo ", "email": "maria.ferraz@unilabs.com", "districtId": 4,
               "districtName": "Bragança", "address": "Rua Abade Tavares, 4, R/C", "latitude": 41.17299,
               "longitude": -7.0484409,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5734, "name": "Unilabs Freixo de Espada à Cinta", "districtId": 4, "districtName": "Bragança",
               "address": "Av.ª Guerra Junqueiro, nº 263", "latitude": 41.086361, "longitude": -6.807988,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5739, "name": "Unilabs Vila Nova de Foz Côa", "email": "ana.martins@unilabs.com", "districtId": 9,
               "districtName": "Guarda", "address": "Rua José Augusto Saraiva de Aguiar, 5", "latitude": 41.08224,
               "longitude": -7.1403598, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5741, "name": "Unilabs Mêda", "email": "susana.lourenco@unilabs.com", "districtId": 9,
               "districtName": "Guarda",
               "address": "Av.ª Gago Coutinho e Sacadura Cabral", "latitude": 40.966407, "longitude": -7.261301,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 5742, "name": "Unilabs Figueira Castelo Rodrigo", "email": "gisela_bento@hotmail.com",
               "districtId": 9,
               "districtName": "Guarda", "address": "Rua Herois de Castelo Rodrigo, 74", "latitude": 40.890987,
               "longitude": 6.96075,
               "specialties": [1, 3, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 5796, "name": "Unilabs Cantanhede | Tocha", "email": "geral.cantanhede@unilabs.com",
               "districtId": 6,
               "districtName": "Coimbra", "address": "Avenida Doutor João Garcia Bacelar, 9015 B, Loja D, R/C",
               "latitude": 40.313857, "longitude": -8.753433, "specialties": [0, 1, 100, 5], "canSchedule": True,
               "isWalkThru": True},
              {"id": 5813, "name": "Unilabs Corgo", "email": "geral@laboratoriopioledo.pt", "districtId": 17,
               "districtName": "Vila Real",
               "address": "Largo do Rossio nº20 Cave \n(entrada pela Avenida 1º de Maio)",
               "latitude": 41.2975274, "longitude": -7.7458038, "specialties": [0, 1, 3, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 6110, "name": "Unilabs Coimbra", "email": "sara.piedade@unilabs.com", "districtId": 6,
               "districtName": "Coimbra", "address": "Rua Luis António Duarte Santos, Nº 16", "latitude": 40.195239,
               "longitude": -8.403525, "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6136, "name": "Unilabs Almada", "email": "3130unilabs@gmail.com", "districtId": 15,
               "districtName": "Setúbal",
               "address": "Praça Lopes Graça, 10-A", "latitude": 38.654516156203485, "longitude": -9.154995159949264,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6149, "name": "Unilabs Lisboa | Alcântara Santo Amaro", "email": "Rececao.Santoamaro@unilabs.com",
               "districtId": 11, "districtName": "Lisboa", "address": "Rua Jau, 18 A ", "latitude": 38.70567,
               "longitude": -9.18363,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6152, "name": "Unilabs Bombarral", "email": "rececao.bombarral@unilabs.com", "districtId": 10,
               "districtName": "Leiria", "address": "Avenida Inocência Cairel Simão 24F", "latitude": 39.27113,
               "longitude": -9.1581,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6157, "name": "Unilabs Lourinhã", "email": "rececao.lourinha@unilabs.com", "districtId": 11,
               "districtName": "Lisboa", "address": "Rua Francisco da Rocha, 47 1º", "latitude": 39.239163,
               "longitude": -9.31135,
               "specialties": [0, 1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6163, "name": "Unilabs Farmácia do NorteShopping", "districtId": 13, "districtName": "Porto",
               "address": "Norteshopping - Rua Sara Afonso, Piso 0, Loja 140", "latitude": 41.180541,
               "longitude": -8.655491,
               "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6177, "name": "Unilabs Cruz de Celas", "districtId": 6, "districtName": "Coimbra",
               "address": "Alameda Calouste Gulbenkian, 9, 2º Andar Sala 26", "latitude": 40.213631286385336,
               "longitude": -8.414251035609965, "specialties": [0, 1, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6180, "name": "Unilabs Santa Clara", "districtId": 6, "districtName": "Coimbra",
               "address": "Rua do Lagar, Lote 6, Loja A, R/C", "latitude": 40.199614267698095,
               "longitude": -8.43985883071185,
               "specialties": [0, 1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6181, "name": "Unilabs Poiares | Largo Daniel de Matos", "districtId": 6,
               "districtName": "Coimbra",
               "address": "Largo Daniel de Matos, R/C Esquerdo", "latitude": 40.21235426558058,
               "longitude": -8.258609411072115,
               "specialties": [0, 1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6539, "name": "Unilabs Rastreio Walk Thru Famalicão", "email": "drivecovidfamalicao@outlook.pt",
               "districtId": 3, "districtName": "Braga", "address": "Alameda Dr. Francisco Sá Carneiro",
               "latitude": 41.407271,
               "longitude": -8.515042, "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6570, "name": "Unilabs Fafe", "districtId": 3, "districtName": "Braga",
               "address": "Avenida Brasil, 162  ",
               "latitude": 41.44886995495103, "longitude": -8.175732545616151, "specialties": [1, 100, 5],
               "canSchedule": True,
               "isWalkThru": True},
              {"id": 6571, "name": "Unilabs Drive Thru Porto", "districtId": 13, "districtName": "Porto",
               "address": "Queimódromo do Porto Estrada da Circunvalação Entrada", "latitude": 41.1730857,
               "longitude": -8.6870413, "specialties": [0, 1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6572, "name": "Unilabs Drive Thru Braga", "districtId": 3, "districtName": "Braga",
               "address": "Altice Forum Braga, Rua Monsenhor Airosa", "latitude": 41.540546, "longitude": -8.42448,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6573, "name": "Unilabs Drive Thru Lisboa", "email": "3123unilabs@gmail.com", "districtId": 11,
               "districtName": "Lisboa", "address": "Rua Vitorino Magalhães Godinho ", "latitude": 38.79540264225093,
               "longitude": -9.093000344601272, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6574, "name": "Unilabs Drive Thru Gaia", "email": "drivegrijo@gmail.com", "districtId": 13,
               "districtName": "Porto", "address": "Espaço Mais Grijó - Rua da Fonte Branca 380", "latitude": 41.039299,
               "longitude": -8.573408, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6576, "name": "Unilabs Drive Thru Lousada", "districtId": 13, "districtName": "Porto",
               "address": "Complexo Desportivo de Lousada", "latitude": 41.287674, "longitude": -8.291555,
               "specialties": [1, 100],
               "canSchedule": True, "isWalkThru": False},
              {"id": 6577, "name": "Unilabs Drive Thru Guimarães", "districtId": 3, "districtName": "Braga",
               "address": "Multiusos de Guimarães, Alameda Cidade de Lisboa 481", "latitude": 41.4352856,
               "longitude": -8.3084307,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6582, "name": "Unilabs Drive Thru Gondomar", "districtId": 13, "districtName": "Porto",
               "address": "Multiusos de Gondomar, Av. Multiusos", "latitude": 41.135402, "longitude": -8.541047,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6637, "name": "Unilabs Drive Thru Almada", "districtId": 15, "districtName": "Setúbal",
               "address": "Av. Aliança Povo M.F.A 855", "latitude": 38.68028131802998, "longitude": -9.149529117620224,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6640, "name": "Unilabs Drive Thru Vila Real", "districtId": 17, "districtName": "Vila Real",
               "address": "Regia-Douro Park - Parque de Ciência e Tecnologia", "latitude": 41.26909,
               "longitude": -7.69598,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6684, "name": "Unilabs Drive Thru Matosinhos", "email": "drivematosinhos@hotmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Parque Manhufe - Rua de Sendim, nº 256", "latitude": 41.1887471,
               "longitude": -8.6779498, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6694, "name": "Unilabs Drive Thru Seixal", "email": "sandra.adao@unilabs.com", "districtId": 15,
               "districtName": "Setúbal", "address": "Parque de Estacionamento do Complexo Desportivo Carla Sacramento",
               "latitude": 38.62788, "longitude": -9.139485, "specialties": [1, 100], "canSchedule": True,
               "isWalkThru": False},
              {"id": 6697, "name": "Unilabs Drive Thru Freamunde", "email": "unilabsdrivefreamunde@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Rua do Sport Clube de Freamunde", "latitude": 41.277513,
               "longitude": -8.338789,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6703, "name": "Unilabs Drive Thru Penafiel (CHTS)", "email": "unilabsdrivepenafiel@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Avenida do Hospital Padre Américo, 210", "latitude": 41.195968,
               "longitude": -8.307313, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6705, "name": "Unilabs Drive Thru Caminha", "districtId": 16, "districtName": "Viana do Castelo",
               "address": "Avenida Doutor Dantas Carneiro", "latitude": 41.879322, "longitude": -8.836975,
               "specialties": [1, 100],
               "canSchedule": True, "isWalkThru": False},
              {"id": 6706, "name": "Unilabs Walk Thru Vizela", "districtId": 3, "districtName": "Braga",
               "address": "Parque de estacionamento do Fórum Vizela -Rua Joaquim Ribeiro Ferreira",
               "latitude": 41.377558,
               "longitude": -8.309727, "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6707, "name": "Unilabs Drive Thru Portimão", "districtId": 8, "districtName": "Faro",
               "address": "Free Parking, Estrada da Rocha  ", "latitude": 37.122, "longitude": -8.535,
               "specialties": [1, 100],
               "canSchedule": True, "isWalkThru": False},
              {"id": 6708, "name": "Unilabs Drive Thru Espinho", "email": "susana.marques.oliveira@unilabs.com",
               "districtId": 1,
               "districtName": "Aveiro", "address": "Parque de Estacionamento da Nave Desportiva de Espinho",
               "latitude": 40.999032,
               "longitude": -8.623842, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6775, "name": "Unilabs Braga - Liberdade 370", "districtId": 3, "districtName": "Braga",
               "address": "Av. da Liberdade, 370 R/C", "latitude": 41.547464, "longitude": -8.4204088,
               "specialties": [0, 1, 100, 5],
               "canSchedule": True, "isWalkThru": True},
              {"id": 6786, "name": "Cristomed | Pombal", "email": "cristo-med@hotmail.com", "districtId": 10,
               "districtName": "Leiria", "address": "Avenida Heróis do Ultramar, nº 60, R/C DTO", "latitude": 39.917222,
               "longitude": -8.623351, "specialties": [1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6787, "name": "Cristomed | Santiago de Litém", "email": "cristo-med@hotmail.com", "districtId": 10,
               "districtName": "Leiria", "address": "Estrada N1-6 Ed. Varandas de Sicó, Loja 3 R/Chão",
               "latitude": 39.087359,
               "longitude": -8.603368, "specialties": [1, 3, 100, 5], "canSchedule": True, "isWalkThru": True},
              {"id": 6804, "name": "Unilabs Drive Thru Monsanto", "districtId": 11, "districtName": "Lisboa",
               "address": "Estádio Pina Manique, Estrada de Monsanto", "latitude": 38.736811, "longitude": -9.202221,
               "specialties": [100], "canSchedule": True, "isWalkThru": False},
              {"id": 6805, "name": "Unilabs Drive Thru Setúbal", "email": "sandra.adao@unilabs.com", "districtId": 15,
               "districtName": "Setúbal", "address": "Estádio do Bonfim", "latitude": 38.5326929,
               "longitude": -8.8910288,
               "specialties": [100], "canSchedule": True, "isWalkThru": False},
              {"id": 6806, "name": "Unilabs Drive Thru Estoril", "districtId": 11, "districtName": "Lisboa",
               "address": "Rua Dom Bosco", "latitude": 38.716624, "longitude": -9.406481, "specialties": [100],
               "canSchedule": True,
               "isWalkThru": False},
              {"id": 6809, "name": "Unilabs Walk Thru Rio Ave", "districtId": 13, "districtName": "Porto",
               "address": " R. Dom Sancho I Estádio do Rio Ave", "latitude": 41.363683,
               "longitude": -8.741048, "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6813, "name": "Unilabs Drive Thru Leiria", "districtId": 10, "districtName": "Leiria",
               "address": "Rua Dom José Alves Correia da Silva, 66", "latitude": 39.729639, "longitude": -8.808464,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6814, "name": "Unilabs Drive Thru Fabril do Barreiro", "email": "sandra.adao@unilabs.com",
               "districtId": 15,
               "districtName": "Setúbal", "address": "Rua do Parque Desportivo da Quimigal, Lavradio",
               "latitude": 38.6593128,
               "longitude": -9.0544148, "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6815, "name": "Unilabs Drive Thru Sintra", "email": "drivesintra.unilabs@gmail.com",
               "districtId": 11,
               "districtName": "Lisboa", "address": "Avenida Dr. Miguel Freire da Cruz – Parque de Estacionamento",
               "latitude": 38.7667165, "longitude": -9.31117, "specialties": [1, 100], "canSchedule": True,
               "isWalkThru": False},
              {"id": 6817, "name": "Unilabs Drive Thru Loures", "email": "driveloures.unilabs@gmail.com",
               "districtId": 11,
               "districtName": "Lisboa", "address": "Passeio do Parque da Cidade", "latitude": 38.8261342,
               "longitude": -9.1611992,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": False},
              {"id": 6820, "name": "Unilabs Drive Thru Odivelas", "email": "driveodivelas.unilabs@gmail.com",
               "districtId": 11,
               "districtName": "Lisboa", "address": "Parque Urbano do Silvado, R. Humberto Ataíde",
               "latitude": 38.78459,
               "longitude": -9.18246, "specialties": [100], "canSchedule": True, "isWalkThru": False},
              {"id": 6822, "name": "Unilabs Walk Thru Gambelas ", "districtId": 8, "districtName": "Faro",
               "address": "Urbanização Casal de Gambelas, Lote 2", "latitude": 37.044987, "longitude": -7.96856,
               "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 6840, "name": "Unilabs Drive Thru Santarém", "email": "drivesantarem.unilabs@gmail.com",
               "districtId": 14,
               "districtName": "Santarém", "address": "Casal do Confeiteiro, Calçadinha, EN3 Rua O, UFCS",
               "latitude": 39.22362,
               "longitude": -8.700018, "specialties": [100], "canSchedule": True, "isWalkThru": False},
              {"id": 6853, "name": "Unilabs Drive Thru Santa Maria Feira", "districtId": 1, "districtName": "Aveiro",
               "address": "Quartel dos Bombeiros V. SMFeira - R. Eng. Duarte Pacheco 20", "latitude": 40.929972,
               "longitude": -8.542473, "specialties": [100], "canSchedule": True, "isWalkThru": False},
              {"id": 6854, "name": "Unilabs Walk Thru Albergaria", "districtId": 1, "districtName": "Aveiro",
               "address": "Rua Marquês de Pombal, Edifício Solmar II, 5, Rés do Chão Esqº",
               "latitude": 40.697759720427115,
               "longitude": -8.487276163188566, "specialties": [1, 100], "canSchedule": True, "isWalkThru": True},
              {"id": 7051, "name": "Unilabs Rastreio Gaia - Jardim do Morro", "email": "walkjardimmorro@gmail.com",
               "districtId": 13,
               "districtName": "Porto", "address": "Jardim do Morro - Av. da República", "latitude": 41.137242,
               "longitude": -8.609256, "specialties": [100], "canSchedule": True, "isWalkThru": True},
              {"id": 7151, "name": "Unilabs Walk Thru Castelo de Paiva", "districtId": 1, "districtName": "Aveiro",
               "address": "Largo Conde de Castelo de Paiva, 123", "latitude": 41.040741, "longitude": -8.271291,
               "specialties": [100], "canSchedule": True, "isWalkThru": True},
              {"id": 7165, "name": "Unilabs Walk Thru Viseu", "email": "hugo.rodrigues@unilabs.com", "districtId": 18,
               "districtName": "Viseu", "address": "Rua Engenheiro Manuel Moreira Amorim", "latitude": 40.648597,
               "longitude": -7.915984, "specialties": [100], "canSchedule": True, "isWalkThru": True},
              {"id": 7176, "name": "Unilabs Walk Thru Viana do Castelo", "districtId": 16,
               "districtName": "Viana do Castelo",
               "address": "Rua de Limia", "latitude": 41.695579, "longitude": -8.577136, "specialties": [100],
               "canSchedule": True,
               "isWalkThru": True},
              {"id": 7177, "name": "Unilabs Walk Thru Ponte de Lima", "districtId": 16,
               "districtName": "Viana do Castelo",
               "address": "Rua Dr. Francisco Sá Carneiro", "latitude": 41.763883, "longitude": -8.577136,
               "specialties": [100],
               "canSchedule": True, "isWalkThru": True},
              {"id": 7189, "name": "Walk Thru Viseu | Casa de Saude Sao Mateus", "email": "lab.cssm@casadesaude.pt",
               "districtId": 18, "districtName": "Viseu", "address": "Rua 5 de Outubro", "latitude": 40.65684,
               "longitude": -7.90505,
               "specialties": [100], "canSchedule": True, "isWalkThru": True},
              {"id": 7203, "name": "Unilabs Drive Thru Famalicão - Trofa", "districtId": 3, "districtName": "Braga",
               "address": "Lago Discount, Lugar do Xisto (Parque de Estacionamento Superior)", "latitude": 41.370188,
               "longitude": -8.551181, "specialties": [100], "canSchedule": True, "isWalkThru": False}]

    test_type = {
        'Particular': 1,
        'SNS': 2
    }
    test_selected = test_type['SNS']
    if test and test in test_type:
        test_selected = test_type[test]

    headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0',
        'Accept': 'application/json',
        'Accept-Language': 'en-US,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate, br',
        'Referer': 'https://go.unilabs.pt/',
        'content-type': 'application/json',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-site',
    }

    if not test_selected:
        test_selected = test_type['SNS']

    today = datetime.today()
    end_date = today + timedelta(days=10)
    today = today.strftime("%Y-%m-%d")
    end_date = end_date.strftime("%Y-%m-%d")

    async with httpx.AsyncClient(timeout=None) as client:
        tasks = [request_data(client, district_id, point, headers, today, end_date, test_selected) for point in points]
        values = await asyncio.gather(*tasks)
        values = list(filter(None, values))
    return values


if __name__ == "__main__":
    unilabs()
